name: frist workflows
on:
  workflow_dispatch:
  push:
    branches:
        - "main"
        
jobs:
  labjob:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: echo 'Hello'
      - name: Second step
        run: echo 'Second step'
      - name: Thrid step
        run: echo 'thrid step' 
  second-job:
    runs-on: ubuntu-latest
    needs: labjob
    steps:
        - name: Start Second job
          run: echo 'Hello Second Job'
